export const metadata = {
  title: "Terms of Use",
  description: "Terms and conditions for using Esteemed Digital's AI services and platforms.",
};

export default function TermsPage() {
  const currentDate = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="min-h-screen bg-white dark:bg-zinc-950">
      <div className="mx-auto max-w-4xl px-6 py-16">
        <div className="prose prose-zinc dark:prose-invert max-w-none">
          <h1 className="text-4xl font-bold text-zinc-900 dark:text-white mb-8">Terms of Use</h1>

          <p className="text-lg text-zinc-600 dark:text-zinc-300 mb-8">
            <strong>Last updated:</strong> {currentDate}
          </p>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Acceptance of Terms</h2>
            <p className="text-zinc-600 dark:text-zinc-300 leading-relaxed">
              By accessing or using Esteemed Digital's AI services, applications, and platforms (the "Services"), you agree to be bound by these Terms of Use ("Terms"). If you do not agree to these Terms, do not use our Services.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Description of Services</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              Esteemed Digital provides artificial intelligence and machine learning services including:
            </p>
            <ul className="list-disc pl-6 mb-6 text-zinc-600 dark:text-zinc-300 space-y-2">
              <li>Esteemed Intelligence - Neural memory and organizational intelligence</li>
              <li>Esteemed AI - Large language models for generation and analysis</li>
              <li>Esteemed Agents - Autonomous AI agents for workflow automation</li>
              <li>AI App Builder - Development tools and APIs</li>
              <li>Human Capital AI - AI solutions for HR and recruiting</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">User Accounts and Registration</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              To access certain features of our Services, you may need to create an account. You agree to:
            </p>
            <ul className="list-disc pl-6 mb-6 text-zinc-600 dark:text-zinc-300 space-y-2">
              <li>Provide accurate, current, and complete information</li>
              <li>Maintain and update your information as necessary</li>
              <li>Keep your account credentials secure and confidential</li>
              <li>Notify us immediately of any unauthorized use</li>
              <li>Be responsible for all activities under your account</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Acceptable Use Policy</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              You agree not to use our Services to:
            </p>
            <ul className="list-disc pl-6 mb-6 text-zinc-600 dark:text-zinc-300 space-y-2">
              <li>Violate any applicable laws or regulations</li>
              <li>Infringe on intellectual property rights</li>
              <li>Generate harmful, offensive, or illegal content</li>
              <li>Attempt to reverse engineer or hack our systems</li>
              <li>Use our Services for competitive intelligence gathering</li>
              <li>Overwhelm our infrastructure or circumvent usage limits</li>
              <li>Share account credentials with unauthorized parties</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Content and Data</h2>

            <h3 className="text-xl font-medium text-zinc-900 dark:text-white mb-3">Your Content</h3>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              You retain ownership of any content you provide to our Services. By using our Services, you grant us a limited license to process your content solely to provide the Services you request.
            </p>

            <h3 className="text-xl font-medium text-zinc-900 dark:text-white mb-3">AI-Generated Content</h3>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              Content generated by our AI models is provided "as is." You are responsible for reviewing and validating any AI-generated content before use. We do not guarantee the accuracy, completeness, or appropriateness of AI-generated content.
            </p>

            <h3 className="text-xl font-medium text-zinc-900 dark:text-white mb-3">Data Security</h3>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              We implement industry-standard security measures to protect your data. However, no system is completely secure, and you acknowledge the inherent risks of transmitting data over the internet.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Subscription and Payment Terms</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              Certain Services require payment of fees:
            </p>
            <ul className="list-disc pl-6 mb-6 text-zinc-600 dark:text-zinc-300 space-y-2">
              <li>Fees are billed in advance for the applicable service period</li>
              <li>All fees are non-refundable except as expressly stated</li>
              <li>We may change our fees with 30 days' notice</li>
              <li>You're responsible for applicable taxes</li>
              <li>Overdue accounts may result in service suspension</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Intellectual Property</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              Our Services, including all underlying technology, algorithms, and software, are protected by intellectual property laws. You may not copy, modify, distribute, or create derivative works without our written permission.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Privacy and Data Processing</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              Our collection and use of your information is governed by our Privacy Policy. By using our Services, you consent to the collection and use of your information as described in our Privacy Policy.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Service Availability</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              We strive to maintain high service availability but do not guarantee uninterrupted access. We may:
            </p>
            <ul className="list-disc pl-6 mb-6 text-zinc-600 dark:text-zinc-300 space-y-2">
              <li>Perform scheduled maintenance with notice</li>
              <li>Make emergency repairs or updates without notice</li>
              <li>Suspend services for violations of these Terms</li>
              <li>Discontinue services with reasonable notice</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Disclaimers and Limitations</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              <strong>DISCLAIMER:</strong> OUR SERVICES ARE PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, AND NON-INFRINGEMENT.
            </p>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              <strong>LIMITATION OF LIABILITY:</strong> TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE SHALL NOT BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES ARISING FROM YOUR USE OF OUR SERVICES.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Indemnification</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              You agree to indemnify and hold harmless Esteemed Digital from any claims, damages, or expenses arising from your use of our Services or violation of these Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Termination</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              Either party may terminate this agreement at any time. Upon termination:
            </p>
            <ul className="list-disc pl-6 mb-6 text-zinc-600 dark:text-zinc-300 space-y-2">
              <li>Your access to our Services will cease</li>
              <li>You remain responsible for any outstanding fees</li>
              <li>We may delete your data after a reasonable period</li>
              <li>Provisions regarding liability and indemnification survive</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Governing Law and Disputes</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              These Terms are governed by the laws of California, USA. Any disputes will be resolved through binding arbitration in San Francisco, California, except for claims that may be brought in small claims court.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Changes to Terms</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              We may update these Terms from time to time. Material changes will be communicated through email or our Services. Continued use after changes constitutes acceptance of the new Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-2xl font-semibold text-zinc-900 dark:text-white mb-4">Contact Information</h2>
            <p className="text-zinc-600 dark:text-zinc-300 mb-4 leading-relaxed">
              Questions about these Terms should be directed to:
            </p>
            <div className="bg-zinc-50 dark:bg-zinc-900 rounded-lg p-6">
              <p className="text-zinc-700 dark:text-zinc-300">
                <strong>Email:</strong> legal@esteemed.digital<br />
                <strong>Address:</strong> Esteemed Digital, 123 Market St, Suite 400, San Francisco, CA 94105<br />
                <strong>Phone:</strong> +1 (555) 123-4567
              </p>
            </div>
          </section>
        </div>
      </div>
    </div>
  );
}
